###
GET http://127.0.0.1:8000/api/api-list/
###

###
GET http://127.0.0.1:8000/api/api-list/668cc90946609801d88cdcbd/call-logs/
###

###
POST http://127.0.0.1:8000/api/api-list/
Content-Type: application/json

{"api_endpoint": "https://jsonplaceholder.typicode.com/todos/3", "request_type": "GET", "params": "None"}
###


###
GET http://127.0.0.1:8000/api/api-list/668d01782d489964ee90e3b3/
###

###
PUT http://127.0.0.1:8000/api/api-list/668d01782d489964ee90e3b3/
Content-Type: application/json

{"api_endpoint": "https://jsonplaceholder.typicode.com/todos/197", "request_type": "GET", "params": "None"}
###

###
PATCH http://127.0.0.1:8000/api/api-list/668ce137cd952bfaab3fa011/
Content-Type: application/json

{
  "api_endpoint": "https://jsonplaceholder.typicode.com/todos/7"
}
###

###
DELETE http://127.0.0.1:8000/api/api-list/668d01782d489964ee90e3b3/
###

###
GET http://127.0.0.1:8000/api/hit-api/668ce0b9514fd7e836b31157/
###

###
GET http://127.0.0.1:8000/api/api-list/668ce086a4c268c294a2e40a/call-logs/
###

#To run celery:
#celery -A cnext_apitracker_backend worker --loglevel=info
#celery -A cnext_apitracker_backend beat --loglevel=info












