###
GET http://127.0.0.1:8000/api/api-list/
###

###
GET http://127.0.0.1:8000/api/api-list/66864cd13212109046cf1f42/call-logs/
###

###
POST http://127.0.0.1:8000/api/api-list/
Content-Type: application/json

{"api_endpoint": "https://jsonplaceholder.typicode.com/todos/21", "request_type": "GET", "params": "None"}
###



###
GET http://127.0.0.1:8000/api/api-list/66864cd13212109046cf1f42/
###

###
PUT http://127.0.0.1:8000/api/api-list/66864cd13212109046cf1f42/
Content-Type: application/json

{"api_endpoint": "https://jsonplaceholder.typicode.com/todos/8", "request_type": "GET", "params": "None"}
###

###
PATCH http://127.0.0.1:8000/api/api-list/66864cd13212109046cf1f42/
Content-Type: application/json

{
  "api_endpoint": "https://jsonplaceholder.typicode.com/todos/7"
}
###

###
DELETE http://127.0.0.1:8000/api/api-list/66864362e342a62535f9a2cb/
###

###
GET http://127.0.0.1:8000/api/hit-api/66864cd13212109046cf1f42/
###

###
GET http://127.0.0.1:8000/api/hit-api/6686b56de3cdf27dd1d3f0a9/
###


#To run celery:
#celery -A cnext_apitracker_backend worker --loglevel=info
#celery -A cnext_apitracker_backend beat --loglevel=info












