# Generated by Django 4.1.13 on 2024-07-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.IntegerField()),
                ('api_endpoint', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Not Ok'), (1, 'Ok')])),
                ('code', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('response_time', models.FloatField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apilist')),
            ],
        ),
    ]
