# Generated by Django 4.2.13 on 2024-07-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.IntegerField(blank=True, null=True)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('params', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Not Ok'), (1, 'Ok')], default=0)),
                ('code', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('response_time', models.FloatField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apilist')),
            ],
        ),
    ]
