# Generated by Django 4.2.13 on 2024-07-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilist',
            name='index_number',
        ),
    ]
